name: replace-in-files
files:
  - 'src/**/*.js'
  - '.*'
  - '*'
  - '!node_modules'
  - '!rif.config.yaml'
replacements:
  - from: /tailwind-plugin-description/g
    to: Tailwind plugin for shorthand border properties.
  - from: /tailwind-plugin/g
    to: ${PROJECT_NAME}
